server :
  port : 80
spring :
  thymeleaf:
    prefix : views/
    suffix : .html
    cache : false 
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/db322?characterEncoding=UTF-8
    username : usr322
    password : 12345678
    
mybatis:
  type-aliases-package: aaa.model
  configration :
    map-underscore-to-camel-case : true 